
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "reunions"
      MYSQL_USER: "amine"
      MYSQL_PASSWORD: "123456"
    volumes:
      - reunions_mariadb-data:/var/lib/mysql
      - ./reunions.sql:/docker-entrypoint-initdb.d/reunions.sql
    networks:
      - reunions_app-network

  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_app
    environment:
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI= 'mysql+pymysql://amine:123456@mariadb/reunions'
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - mariadb
    networks:
      - reunions_app-network

volumes:
  reunions_mariadb-data:

networks:
  reunions_app-network:
    driver: bridge

